apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portfoli
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`santi.ramisclar.cat`)
      kind: Rule
      services:
        - name: portfoli
          port: 80
      middlewares:
        - name: security-headers
          namespace: default
  tls:
    certResolver: letsencrypt-prod
    domains:
      - main: santi.ramisclar.cat